import type { APIRoute } from 'astro';
import bank from '../../../data/quiz-questions-Claude.json';

// Static question bank behind /quiz/, generated by scripts/quiz-Claude.mjs
// from data/buried-Claude.json + data/cemeteries-Claude.json (Wikidata,
// CC0). Served as its own endpoint rather than inlined into the quiz page's
// HTML: the bank is ~570 KB, so the page fetches it client-side only once a
// visitor actually starts a round, keeping the page's own markup light.
//
// Shape (see scripts/quiz-Claude.mjs for the generator):
//   {
//     generated_at, source, seed,
//     modes: {
//       buried_where:     { title, description, questions: Question[] },
//       cemetery_trivia:  { title, description, questions: Question[] },
//       mystery_grid:     { title, description, questions: Question[] },
//     }
//   }
//   Question = {
//     id: string,
//     mode: 'buried_where' | 'cemetery_trivia' | 'mystery_grid',
//     template: string,
//     prompt?: string,       // buried_where, cemetery_trivia
//     clues?: string[],      // mystery_grid (3 real, field-derived clues)
//     choices: string[],     // always length 4, always real dataset values
//     answerIndex: number,   // index into choices of the correct one
//     citation: { person_qid?, wikidata_qid?, cemetery_slug? }, // real QIDs
//     link: string,          // path to the real cemetery/person page
//     note?: string,         // optional plain factual note (e.g. military term)
//   }
export const GET: APIRoute = async () => {
  return new Response(JSON.stringify(bank), {
    headers: { 'content-type': 'application/json; charset=utf-8' },
  });
};
